sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-new  -f Dockerfile.dev .

script:
  - docker run docker-react-new npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-new"
  env: "DockerReactNew-env"
  bucket_name: "elasticbeanstalk-us-east-2-988585708477"
  bucket_path: "docker-react-new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id:
    secure: "$AWS_SECRET_KEY"
